API/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers
{
    public class ErrorController : Controller
    {
        [Route("Error/{statusCode}")]
        public IActionResult HttpStatusCodeHandler(int statusCode)
        {
            switch (statusCode)
            {
                case 404:
                    ViewBag.ErrorMessage = "Sorry, the resource you requested could not be found";
                    break;
            }
            return View("ErrorView");
        }
    }
}

API/Controllers/RolesController.cs
using API.ViewModels;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    //[Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

API/Controllers/UserAssignmentController.cs
using API.ViewModels;
using BLL.DTO;
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;

namespace API.Controllers
{
    public class UserAssignmentController : Controller
    {
        private readonly IAssignmentService _Assignment;
        private readonly IUserAssignmentService _UserAssignment;
        private readonly Microsoft.Extensions.Configuration.IConfiguration _configuration;
        private UserManager<User> _userManager;

        public UserAssignmentController(IAssignmentService iAllAssignments, IUserAssignmentService userAssignment, 
            UserManager<User> userManager, Microsoft.Extensions.Configuration.IConfiguration configuration)
        {
            _Assignment = iAllAssignments;
            _userManager = userManager;
            _UserAssignment = userAssignment;
            _configuration = configuration;
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddToUser(string userId, string assignmentId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            AssignmentDTO assignment = _Assignment.GetAssignment(assignmentId);
            if (user == null)
            {
                return NotFound();
            }
            if (assignment == null)
            {
                return NotFound();
            }
            _UserAssignment.AddUserAssignment(assignment, user);
            /*string hostemail = _configuration.GetValue<string>("MySettings:Email");
            string hosppassword = _configuration.GetValue<string>("MySettings:Password");
            int port = _configuration.GetValue<int>("MySettings:SMTPPort");
            EmailService emailService = new EmailService();
            await emailService.SendEmailAsync(user.Email, "You resieved a new assignment XD", 
                $"We granted you a new assignment =) {assignment.Name}, please check it", hostemail, hosppassword, port);*/
            return RedirectToAction("Index", "Users", userId);
        }
        public async Task<IActionResult> ShowUserAssignments(string userName)
        {
            User user = await _userManager.FindByNameAsync(userName);
            if (user == null)
            {
                return NotFound();
            }
            List<AssignmentDTO> assignments = _UserAssignment.GetAssignments(user);
            var assignmentObj = new AssignmentListViewModel
            {
                AllAssignments = assignments,
            };
            return View(assignmentObj);
        }
        public async Task<IActionResult> MarkComplete(string userName, string assignmentId)
        {
            User user = await _userManager.FindByNameAsync(userName);
            AssignmentDTO assignment = _Assignment.GetAssignment(assignmentId);
            if (user == null)
            {
                return NotFound();
            }
            if (assignment == null)
            {
                return NotFound();
            }
            _UserAssignment.MarkAsComplete(assignment, user);
            string id = assignment.Id;
            return RedirectToAction("Index", "Home");
        }
        public ViewResult List()
        {
            IEnumerable<UserAssignmentDTO> userAssignments = _UserAssignment.UserAssignments().OrderBy(x => x.Id);
            var userAssignmentObj = new UserAssignmentListViewModel
            {
                AllUserAssignments = userAssignments
            };
            return View(userAssignmentObj);
        }
        public ViewResult ShowUserAssignment(string id)
        {
            UserAssignmentDTO userAssignment = _UserAssignment.GetUserAssignment(id);
            var userAssignmentObj = new UserAssignmentListViewModel
            {
                CurrAssignment = userAssignment.Assignment,
                Worker = userAssignment.User,
                UserAssignment = userAssignment
            };
            return View(userAssignmentObj);
        }
    }
}

API/Controllers/UsersController.cs
using API.ViewModels;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    //[Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

API/Views/Shared/ErrorView.cshtml
@{
    ViewBag.Title = "Error";
}
<h3>@ViewBag.ErrorMessage</h3>

API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Dimask</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Assignments" asp-action="List">Assignments</a>
                    </li>
                    @if (User.IsInRole("moderator") || User.IsInRole("admin") || User.IsInRole("guest"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="UserAssignment" asp-action="List">Checkout</a>
                        </li>
                        @if (User.IsInRole("admin") || User.IsInRole("guest"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link" asp-controller="UserAssignment" asp-action="ShowUserAssignments" 
                           asp-route-userName="@User.Identity.Name">@User.Identity.Name</a>
                        <form method="post" asp-controller="Account" asp-action="Logout">
                            <input type="submit" value="Logout" class="btn btn-outline-secondary"/>
                        </form>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2020 Vovchenko · <a href="#">Privacy</a></p>
    </footer>
</body>
</html>