API/Controllers/AssignmentController.cs
using API.ViewModels;
using BLL.DTO;
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    //[Authorize(Roles = "moderator, admin")]
    public class AssignmentController : Controller
    {
        private readonly IAssignmentService _Assignment;
        private readonly IUserAssignmentService _UserAssignment;
        private UserManager<User> _userManager;

        public AssignmentController(IAssignmentService iAllAssignments, IUserAssignmentService userAssignment, UserManager<User> userManager)
        {
            _Assignment = iAllAssignments;
            _userManager = userManager;
            _UserAssignment = userAssignment;
        }
        
        [Route("Assignments/List")]
        public ViewResult List()
        {
            IEnumerable<AssignmentDTO> assignments = _Assignment.Assignments().OrderBy(x => x.Id);
            var assignmentObj = new AssignmentListViewModel
            {
                AllAssignments = assignments
            };

            ViewBag.Title = "Assignment list";
            return View(assignmentObj);
        }
        public ViewResult AddList(string userId)
        {
            IEnumerable<AssignmentDTO> assignments = _Assignment.Assignments().OrderBy(x => x.Id);
            var assignmentObj = new AssignmentListViewModel
            {
                AllAssignments = assignments,
                UserId = userId
            };

            ViewBag.Title = "Assignment list";
            return View(assignmentObj);
        }
        public IActionResult CreateAssignment()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateAssignment(AssignmentDTO assignment)
        {
            if (ModelState.IsValid)
            {
                _Assignment.AddAssignment(assignment);
                return RedirectToAction("List");
            }
            return View(assignment);
        }
        public ViewResult ShowAssignment(string id)
        {
            var assignment = _Assignment.GetAssignment(id);
            var assignmentObj = new AssignmentListViewModel
            {
                CurrAssignment = assignment
            };
            return View(assignmentObj);
        }
        [HttpPost]
        public async Task<IActionResult> ShowAssignment(AssignmentListViewModel model, string assignmentId)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                AssignmentDTO assignment = _Assignment.GetAssignment(assignmentId);
                _UserAssignment.AddSolution(assignment, user, model.Text);
            }
            return RedirectToAction("Index", "Home");
        }
        public IActionResult DeleteAssignment(string id)
        {
            _UserAssignment.DeleteUserAssignment(id);
            _Assignment.DeleteAssignment(id);
            return RedirectToAction("List");
        }
    }
}

API/Controllers/UserAssignmentController.cs
using API.ViewModels;
using BLL.DTO;
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;

namespace API.Controllers
{
    public class UserAssignmentController : Controller
    {
        private readonly IAssignmentService _Assignment;
        private readonly IUserAssignmentService _UserAssignment;
        private readonly Microsoft.Extensions.Configuration.IConfiguration _configuration;
        private UserManager<User> _userManager;

        public UserAssignmentController(IAssignmentService iAllAssignments, IUserAssignmentService userAssignment, 
            UserManager<User> userManager, Microsoft.Extensions.Configuration.IConfiguration configuration)
        {
            _Assignment = iAllAssignments;
            _userManager = userManager;
            _UserAssignment = userAssignment;
            _configuration = configuration;
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddToUser(string userId, string assignmentId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            AssignmentDTO assignment = _Assignment.GetAssignment(assignmentId);
            if (user == null)
            {
                return NotFound();
            }
            if (assignment == null)
            {
                return NotFound();
            }
            _UserAssignment.AddUserAssignment(assignment, user);
            /*string hostemail = _configuration.GetValue<string>("MySettings:Email");
            string hosppassword = _configuration.GetValue<string>("MySettings:Password");
            int port = _configuration.GetValue<int>("MySettings:SMTPPort");
            EmailService emailService = new EmailService();
            await emailService.SendEmailAsync(user.Email, "You resieved a new assignment XD", 
                $"We granted you a new assignment =) {assignment.Name}, please check it", hostemail, hosppassword, port);*/
            return RedirectToAction("Index", "Users", userId);
        }
        public async Task<IActionResult> ShowUserAssignments(string userName)
        {
            User user = await _userManager.FindByNameAsync(userName);
            if (user == null)
            {
                return NotFound();
            }
            List<AssignmentDTO> assignments = _UserAssignment.GetAssignments(user);
            var assignmentObj = new AssignmentListViewModel
            {
                AllAssignments = assignments,
            };
            return View(assignmentObj);
        }
        public async Task<IActionResult> MarkComplete(string userName, string assignmentId)
        {
            User user = await _userManager.FindByNameAsync(userName);
            AssignmentDTO assignment = _Assignment.GetAssignment(assignmentId);
            if (user == null)
            {
                return NotFound();
            }
            if (assignment == null)
            {
                return NotFound();
            }
            _UserAssignment.MarkAsComplete(assignment, user);
            string id = assignment.Id;
            return RedirectToAction("Index", "Home");
        }
        public ViewResult List()
        {
            IEnumerable<UserAssignmentDTO> userAssignments = _UserAssignment.UserAssignments().OrderBy(x => x.Id);
            var userAssignmentObj = new UserAssignmentListViewModel
            {
                AllUserAssignments = userAssignments
            };
            return View(userAssignmentObj);
        }
        public ViewResult ShowUserAssignment(string id)
        {
            UserAssignmentDTO userAssignment = _UserAssignment.GetUserAssignment(id);
            var userAssignmentObj = new UserAssignmentListViewModel
            {
                CurrAssignment = userAssignment.Assignment,
                Worker = userAssignment.User,
                UserAssignment = userAssignment
            };
            return View(userAssignmentObj);
        }
    }
}

API/Views/UserAssignment/List.cshtml
@model UserAssignmentListViewModel
    <div class="container">
        @foreach (var userAssignment in Model.AllUserAssignments)
        {
            int time = DateTime.Now.CompareTo(userAssignment.Assignment.EndTime);
            if (userAssignment.IsCompleted || time == 1)
            {
                <div class="alert alert-warning mt-3">
                    <b>Assigmnent:</b> @userAssignment.Assignment.Name<br />
                    <b>Start Time:</b> @userAssignment.Assignment.StartTime<br />
                    <b>End Time:</b> @userAssignment.Assignment.EndTime<br />
                    <p>
                        <a class="btn btn-sm btn-primary" asp-controller="UserAssignment"
                           asp-action="ShowUserAssignment" asp-route-id="@userAssignment.Id">Check</a>
                    </p>
                </div>
            }
        }
        <br />
    </div>

API/Views/UserAssignment/ShowUserAssignment.cshtml
@model UserAssignmentListViewModel
<div class="container">
    <div>
        <b>Assigmnent:</b> @Model.CurrAssignment.Name<br />
        <b>User:</b> @Model.Worker.UserName<br />
        <b>Start Time:</b> @Model.CurrAssignment.StartTime<br />
        <b>End Time:</b> @Model.CurrAssignment.EndTime<br />
        @{
            long duration = Model.CurrAssignment.EndTime.Ticks - Model.CurrAssignment.StartTime.Ticks;
            long passed = DateTime.Now.Ticks - Model.CurrAssignment.StartTime.Ticks;
        }
        <label for="task">Assignment time:</label>
        <progress id="task" max=@duration value=@passed></progress><br />
        <b>Detail:</b> @Model.CurrAssignment.Description<br />
        <b>Solution:</b> @Model.UserAssignment.Text<br />
    </div>
</div>

API/Views/UserAssignment/ShowUserAssignments.cshtml
@model AssignmentListViewModel
<div class="container">
    @foreach (var assignment in Model.AllAssignments)
    {
    <div class="alert alert-warning mt-3">
        <b>Assigmnent:</b> @assignment.Name<br />
        <b>Start Time:</b> @assignment.StartTime<br />
        <b>End Time:</b> @assignment.EndTime<br />
        <p><a class="btn btn-sm btn-primary" asp-controller="Assignment" asp-action="ShowAssignment" asp-route-id="@assignment.Id">Details</a></p>
    </div>
    }
</div>