API/Controllers/AssignmentController.cs
using API.ViewModels;
using BLL.DTO;
using BLL.Interfaces;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    //[Authorize(Roles = "moderator, admin")]
    public class AssignmentController : Controller
    {
        private readonly IAssignmentService _Assignment;
        private readonly IUserAssignmentService _UserAssignment;
        private UserManager<User> _userManager;

        public AssignmentController(IAssignmentService iAllAssignments, IUserAssignmentService userAssignment, UserManager<User> userManager)
        {
            _Assignment = iAllAssignments;
            _userManager = userManager;
            _UserAssignment = userAssignment;
        }
        
        [Route("Assignments/List")]
        public ViewResult List()
        {
            IEnumerable<AssignmentDTO> assignments = _Assignment.Assignments().OrderBy(x => x.Id);
            var assignmentObj = new AssignmentListViewModel
            {
                AllAssignments = assignments
            };

            ViewBag.Title = "Assignment list";
            return View(assignmentObj);
        }
        public ViewResult AddList(string userId)
        {
            IEnumerable<AssignmentDTO> assignments = _Assignment.Assignments().OrderBy(x => x.Id);
            var assignmentObj = new AssignmentListViewModel
            {
                AllAssignments = assignments,
                UserId = userId
            };

            ViewBag.Title = "Assignment list";
            return View(assignmentObj);
        }
        public IActionResult CreateAssignment()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateAssignment(AssignmentDTO assignment)
        {
            if (ModelState.IsValid)
            {
                _Assignment.AddAssignment(assignment);
                return RedirectToAction("List");
            }
            return View(assignment);
        }
        public ViewResult ShowAssignment(string id)
        {
            var assignment = _Assignment.GetAssignment(id);
            var assignmentObj = new AssignmentListViewModel
            {
                CurrAssignment = assignment
            };
            return View(assignmentObj);
        }
        [HttpPost]
        public async Task<IActionResult> ShowAssignment(AssignmentListViewModel model, string assignmentId)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                AssignmentDTO assignment = _Assignment.GetAssignment(assignmentId);
                _UserAssignment.AddSolution(assignment, user, model.Text);
            }
            return RedirectToAction("Index", "Home");
        }
        public IActionResult DeleteAssignment(string id)
        {
            _UserAssignment.DeleteUserAssignment(id);
            _Assignment.DeleteAssignment(id);
            return RedirectToAction("List");
        }
    }
}

API/Controllers/UsersController.cs
using API.ViewModels;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace API.Controllers
{
    //[Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

API/Views/Users/Create.cshtml
@model CreateUserViewModel
@{
    ViewBag.Title = "Add user";
}
<form asp-action="Create" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Пароль</label>
        <input type="password" asp-for="Password" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-outline-secondary" />
    </div>
</form>

API/Views/Users/Edit.cshtml
@model EditUserViewModel
@{
    ViewBag.Title = "Edit user";
}
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-outline-secondary" />
    </div>
</form>

API/Views/Users/Index.cshtml
@model IEnumerable<DAL.Models.User>
@{
    ViewBag.Title = "Users List";
}

<a asp-action="Create">Add user</a>

<table class="table">
    <tr><th>Email</th><th></th></tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-controller="Assignment" asp-action="AddList" asp-route-userId="@user.Id">Add assignmnt</a>
                    <a class="btn btn-sm btn-primary" asp-controller="User" asp-action="Edit" asp-route-userId="@user.Id">Edit</a>
                </form>
            </td>
        </tr>
    }
</table>